/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125BooksIndexRouteImport } from './routes/{-$locale}/books/index'
import { Route as Char123LocaleChar125BooksIdRouteRouteImport } from './routes/{-$locale}/books/$id/route'
import { Route as Char123LocaleChar125BooksNewIndexRouteImport } from './routes/{-$locale}/books/new/index'
import { Route as Char123LocaleChar125BooksIdIndexRouteImport } from './routes/{-$locale}/books/$id/index'
import { Route as Char123LocaleChar125BooksIdEditIndexRouteImport } from './routes/{-$locale}/books/$id/edit/index'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125BooksIndexRoute =
  Char123LocaleChar125BooksIndexRouteImport.update({
    id: '/books/',
    path: '/books/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125BooksIdRouteRoute =
  Char123LocaleChar125BooksIdRouteRouteImport.update({
    id: '/books/$id',
    path: '/books/$id',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125BooksNewIndexRoute =
  Char123LocaleChar125BooksNewIndexRouteImport.update({
    id: '/books/new/',
    path: '/books/new/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125BooksIdIndexRoute =
  Char123LocaleChar125BooksIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125BooksIdRouteRoute,
  } as any)
const Char123LocaleChar125BooksIdEditIndexRoute =
  Char123LocaleChar125BooksIdEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => Char123LocaleChar125BooksIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/books/$id': typeof Char123LocaleChar125BooksIdRouteRouteWithChildren
  '/{-$locale}/books/': typeof Char123LocaleChar125BooksIndexRoute
  '/{-$locale}/books/$id/': typeof Char123LocaleChar125BooksIdIndexRoute
  '/{-$locale}/books/new/': typeof Char123LocaleChar125BooksNewIndexRoute
  '/{-$locale}/books/$id/edit/': typeof Char123LocaleChar125BooksIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/books': typeof Char123LocaleChar125BooksIndexRoute
  '/{-$locale}/books/$id': typeof Char123LocaleChar125BooksIdIndexRoute
  '/{-$locale}/books/new': typeof Char123LocaleChar125BooksNewIndexRoute
  '/{-$locale}/books/$id/edit': typeof Char123LocaleChar125BooksIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/books/$id': typeof Char123LocaleChar125BooksIdRouteRouteWithChildren
  '/{-$locale}/books/': typeof Char123LocaleChar125BooksIndexRoute
  '/{-$locale}/books/$id/': typeof Char123LocaleChar125BooksIdIndexRoute
  '/{-$locale}/books/new/': typeof Char123LocaleChar125BooksNewIndexRoute
  '/{-$locale}/books/$id/edit/': typeof Char123LocaleChar125BooksIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/books/$id'
    | '/{-$locale}/books/'
    | '/{-$locale}/books/$id/'
    | '/{-$locale}/books/new/'
    | '/{-$locale}/books/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/{-$locale}/books'
    | '/{-$locale}/books/$id'
    | '/{-$locale}/books/new'
    | '/{-$locale}/books/$id/edit'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/books/$id'
    | '/{-$locale}/books/'
    | '/{-$locale}/books/$id/'
    | '/{-$locale}/books/new/'
    | '/{-$locale}/books/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/books/': {
      id: '/{-$locale}/books/'
      path: '/books'
      fullPath: '/{-$locale}/books/'
      preLoaderRoute: typeof Char123LocaleChar125BooksIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/books/$id': {
      id: '/{-$locale}/books/$id'
      path: '/books/$id'
      fullPath: '/{-$locale}/books/$id'
      preLoaderRoute: typeof Char123LocaleChar125BooksIdRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/books/new/': {
      id: '/{-$locale}/books/new/'
      path: '/books/new'
      fullPath: '/{-$locale}/books/new/'
      preLoaderRoute: typeof Char123LocaleChar125BooksNewIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/books/$id/': {
      id: '/{-$locale}/books/$id/'
      path: '/'
      fullPath: '/{-$locale}/books/$id/'
      preLoaderRoute: typeof Char123LocaleChar125BooksIdIndexRouteImport
      parentRoute: typeof Char123LocaleChar125BooksIdRouteRoute
    }
    '/{-$locale}/books/$id/edit/': {
      id: '/{-$locale}/books/$id/edit/'
      path: '/edit'
      fullPath: '/{-$locale}/books/$id/edit/'
      preLoaderRoute: typeof Char123LocaleChar125BooksIdEditIndexRouteImport
      parentRoute: typeof Char123LocaleChar125BooksIdRouteRoute
    }
  }
}

interface Char123LocaleChar125BooksIdRouteRouteChildren {
  Char123LocaleChar125BooksIdIndexRoute: typeof Char123LocaleChar125BooksIdIndexRoute
  Char123LocaleChar125BooksIdEditIndexRoute: typeof Char123LocaleChar125BooksIdEditIndexRoute
}

const Char123LocaleChar125BooksIdRouteRouteChildren: Char123LocaleChar125BooksIdRouteRouteChildren =
  {
    Char123LocaleChar125BooksIdIndexRoute:
      Char123LocaleChar125BooksIdIndexRoute,
    Char123LocaleChar125BooksIdEditIndexRoute:
      Char123LocaleChar125BooksIdEditIndexRoute,
  }

const Char123LocaleChar125BooksIdRouteRouteWithChildren =
  Char123LocaleChar125BooksIdRouteRoute._addFileChildren(
    Char123LocaleChar125BooksIdRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125BooksIdRouteRoute: typeof Char123LocaleChar125BooksIdRouteRouteWithChildren
  Char123LocaleChar125BooksIndexRoute: typeof Char123LocaleChar125BooksIndexRoute
  Char123LocaleChar125BooksNewIndexRoute: typeof Char123LocaleChar125BooksNewIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125BooksIdRouteRoute:
      Char123LocaleChar125BooksIdRouteRouteWithChildren,
    Char123LocaleChar125BooksIndexRoute: Char123LocaleChar125BooksIndexRoute,
    Char123LocaleChar125BooksNewIndexRoute:
      Char123LocaleChar125BooksNewIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
