/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125DefaultRouteRouteImport } from './routes/{-$locale}/_default/route'
import { Route as Char123LocaleChar125AuthRouteRouteImport } from './routes/{-$locale}/_auth/route'
import { Route as Char123LocaleChar125DefaultIndexRouteImport } from './routes/{-$locale}/_default/index'
import { Route as Char123LocaleChar125AuthLoginRouteImport } from './routes/{-$locale}/_auth/login'
import { Route as Char123LocaleChar125DefaultBooksIndexRouteImport } from './routes/{-$locale}/_default/books/index'
import { Route as Char123LocaleChar125DefaultBooksIdRouteRouteImport } from './routes/{-$locale}/_default/books/$id/route'
import { Route as Char123LocaleChar125DefaultBooksNewIndexRouteImport } from './routes/{-$locale}/_default/books/new/index'
import { Route as Char123LocaleChar125DefaultBooksIdIndexRouteImport } from './routes/{-$locale}/_default/books/$id/index'
import { Route as Char123LocaleChar125DefaultBooksIdEditIndexRouteImport } from './routes/{-$locale}/_default/books/$id/edit/index'

const Char123LocaleChar125DefaultRouteRoute =
  Char123LocaleChar125DefaultRouteRouteImport.update({
    id: '/{-$locale}/_default',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthRouteRoute =
  Char123LocaleChar125AuthRouteRouteImport.update({
    id: '/{-$locale}/_auth',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DefaultIndexRoute =
  Char123LocaleChar125DefaultIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125DefaultRouteRoute,
  } as any)
const Char123LocaleChar125AuthLoginRoute =
  Char123LocaleChar125AuthLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125AuthRouteRoute,
  } as any)
const Char123LocaleChar125DefaultBooksIndexRoute =
  Char123LocaleChar125DefaultBooksIndexRouteImport.update({
    id: '/books/',
    path: '/books/',
    getParentRoute: () => Char123LocaleChar125DefaultRouteRoute,
  } as any)
const Char123LocaleChar125DefaultBooksIdRouteRoute =
  Char123LocaleChar125DefaultBooksIdRouteRouteImport.update({
    id: '/books/$id',
    path: '/books/$id',
    getParentRoute: () => Char123LocaleChar125DefaultRouteRoute,
  } as any)
const Char123LocaleChar125DefaultBooksNewIndexRoute =
  Char123LocaleChar125DefaultBooksNewIndexRouteImport.update({
    id: '/books/new/',
    path: '/books/new/',
    getParentRoute: () => Char123LocaleChar125DefaultRouteRoute,
  } as any)
const Char123LocaleChar125DefaultBooksIdIndexRoute =
  Char123LocaleChar125DefaultBooksIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125DefaultBooksIdRouteRoute,
  } as any)
const Char123LocaleChar125DefaultBooksIdEditIndexRoute =
  Char123LocaleChar125DefaultBooksIdEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => Char123LocaleChar125DefaultBooksIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125DefaultRouteRouteWithChildren
  '/{-$locale}/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/': typeof Char123LocaleChar125DefaultIndexRoute
  '/{-$locale}/books/$id': typeof Char123LocaleChar125DefaultBooksIdRouteRouteWithChildren
  '/{-$locale}/books/': typeof Char123LocaleChar125DefaultBooksIndexRoute
  '/{-$locale}/books/$id/': typeof Char123LocaleChar125DefaultBooksIdIndexRoute
  '/{-$locale}/books/new/': typeof Char123LocaleChar125DefaultBooksNewIndexRoute
  '/{-$locale}/books/$id/edit/': typeof Char123LocaleChar125DefaultBooksIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125DefaultIndexRoute
  '/{-$locale}/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/books': typeof Char123LocaleChar125DefaultBooksIndexRoute
  '/{-$locale}/books/$id': typeof Char123LocaleChar125DefaultBooksIdIndexRoute
  '/{-$locale}/books/new': typeof Char123LocaleChar125DefaultBooksNewIndexRoute
  '/{-$locale}/books/$id/edit': typeof Char123LocaleChar125DefaultBooksIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/_auth': typeof Char123LocaleChar125AuthRouteRouteWithChildren
  '/{-$locale}/_default': typeof Char123LocaleChar125DefaultRouteRouteWithChildren
  '/{-$locale}/_auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/_default/': typeof Char123LocaleChar125DefaultIndexRoute
  '/{-$locale}/_default/books/$id': typeof Char123LocaleChar125DefaultBooksIdRouteRouteWithChildren
  '/{-$locale}/_default/books/': typeof Char123LocaleChar125DefaultBooksIndexRoute
  '/{-$locale}/_default/books/$id/': typeof Char123LocaleChar125DefaultBooksIdIndexRoute
  '/{-$locale}/_default/books/new/': typeof Char123LocaleChar125DefaultBooksNewIndexRoute
  '/{-$locale}/_default/books/$id/edit/': typeof Char123LocaleChar125DefaultBooksIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/login'
    | '/{-$locale}/'
    | '/{-$locale}/books/$id'
    | '/{-$locale}/books/'
    | '/{-$locale}/books/$id/'
    | '/{-$locale}/books/new/'
    | '/{-$locale}/books/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/{-$locale}/login'
    | '/{-$locale}/books'
    | '/{-$locale}/books/$id'
    | '/{-$locale}/books/new'
    | '/{-$locale}/books/$id/edit'
  id:
    | '__root__'
    | '/{-$locale}/_auth'
    | '/{-$locale}/_default'
    | '/{-$locale}/_auth/login'
    | '/{-$locale}/_default/'
    | '/{-$locale}/_default/books/$id'
    | '/{-$locale}/_default/books/'
    | '/{-$locale}/_default/books/$id/'
    | '/{-$locale}/_default/books/new/'
    | '/{-$locale}/_default/books/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125AuthRouteRoute: typeof Char123LocaleChar125AuthRouteRouteWithChildren
  Char123LocaleChar125DefaultRouteRoute: typeof Char123LocaleChar125DefaultRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/_default': {
      id: '/{-$locale}/_default'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125DefaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_auth': {
      id: '/{-$locale}/_auth'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_default/': {
      id: '/{-$locale}/_default/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125DefaultIndexRouteImport
      parentRoute: typeof Char123LocaleChar125DefaultRouteRoute
    }
    '/{-$locale}/_auth/login': {
      id: '/{-$locale}/_auth/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125AuthLoginRouteImport
      parentRoute: typeof Char123LocaleChar125AuthRouteRoute
    }
    '/{-$locale}/_default/books/': {
      id: '/{-$locale}/_default/books/'
      path: '/books'
      fullPath: '/{-$locale}/books/'
      preLoaderRoute: typeof Char123LocaleChar125DefaultBooksIndexRouteImport
      parentRoute: typeof Char123LocaleChar125DefaultRouteRoute
    }
    '/{-$locale}/_default/books/$id': {
      id: '/{-$locale}/_default/books/$id'
      path: '/books/$id'
      fullPath: '/{-$locale}/books/$id'
      preLoaderRoute: typeof Char123LocaleChar125DefaultBooksIdRouteRouteImport
      parentRoute: typeof Char123LocaleChar125DefaultRouteRoute
    }
    '/{-$locale}/_default/books/new/': {
      id: '/{-$locale}/_default/books/new/'
      path: '/books/new'
      fullPath: '/{-$locale}/books/new/'
      preLoaderRoute: typeof Char123LocaleChar125DefaultBooksNewIndexRouteImport
      parentRoute: typeof Char123LocaleChar125DefaultRouteRoute
    }
    '/{-$locale}/_default/books/$id/': {
      id: '/{-$locale}/_default/books/$id/'
      path: '/'
      fullPath: '/{-$locale}/books/$id/'
      preLoaderRoute: typeof Char123LocaleChar125DefaultBooksIdIndexRouteImport
      parentRoute: typeof Char123LocaleChar125DefaultBooksIdRouteRoute
    }
    '/{-$locale}/_default/books/$id/edit/': {
      id: '/{-$locale}/_default/books/$id/edit/'
      path: '/edit'
      fullPath: '/{-$locale}/books/$id/edit/'
      preLoaderRoute: typeof Char123LocaleChar125DefaultBooksIdEditIndexRouteImport
      parentRoute: typeof Char123LocaleChar125DefaultBooksIdRouteRoute
    }
  }
}

interface Char123LocaleChar125AuthRouteRouteChildren {
  Char123LocaleChar125AuthLoginRoute: typeof Char123LocaleChar125AuthLoginRoute
}

const Char123LocaleChar125AuthRouteRouteChildren: Char123LocaleChar125AuthRouteRouteChildren =
  {
    Char123LocaleChar125AuthLoginRoute: Char123LocaleChar125AuthLoginRoute,
  }

const Char123LocaleChar125AuthRouteRouteWithChildren =
  Char123LocaleChar125AuthRouteRoute._addFileChildren(
    Char123LocaleChar125AuthRouteRouteChildren,
  )

interface Char123LocaleChar125DefaultBooksIdRouteRouteChildren {
  Char123LocaleChar125DefaultBooksIdIndexRoute: typeof Char123LocaleChar125DefaultBooksIdIndexRoute
  Char123LocaleChar125DefaultBooksIdEditIndexRoute: typeof Char123LocaleChar125DefaultBooksIdEditIndexRoute
}

const Char123LocaleChar125DefaultBooksIdRouteRouteChildren: Char123LocaleChar125DefaultBooksIdRouteRouteChildren =
  {
    Char123LocaleChar125DefaultBooksIdIndexRoute:
      Char123LocaleChar125DefaultBooksIdIndexRoute,
    Char123LocaleChar125DefaultBooksIdEditIndexRoute:
      Char123LocaleChar125DefaultBooksIdEditIndexRoute,
  }

const Char123LocaleChar125DefaultBooksIdRouteRouteWithChildren =
  Char123LocaleChar125DefaultBooksIdRouteRoute._addFileChildren(
    Char123LocaleChar125DefaultBooksIdRouteRouteChildren,
  )

interface Char123LocaleChar125DefaultRouteRouteChildren {
  Char123LocaleChar125DefaultIndexRoute: typeof Char123LocaleChar125DefaultIndexRoute
  Char123LocaleChar125DefaultBooksIdRouteRoute: typeof Char123LocaleChar125DefaultBooksIdRouteRouteWithChildren
  Char123LocaleChar125DefaultBooksIndexRoute: typeof Char123LocaleChar125DefaultBooksIndexRoute
  Char123LocaleChar125DefaultBooksNewIndexRoute: typeof Char123LocaleChar125DefaultBooksNewIndexRoute
}

const Char123LocaleChar125DefaultRouteRouteChildren: Char123LocaleChar125DefaultRouteRouteChildren =
  {
    Char123LocaleChar125DefaultIndexRoute:
      Char123LocaleChar125DefaultIndexRoute,
    Char123LocaleChar125DefaultBooksIdRouteRoute:
      Char123LocaleChar125DefaultBooksIdRouteRouteWithChildren,
    Char123LocaleChar125DefaultBooksIndexRoute:
      Char123LocaleChar125DefaultBooksIndexRoute,
    Char123LocaleChar125DefaultBooksNewIndexRoute:
      Char123LocaleChar125DefaultBooksNewIndexRoute,
  }

const Char123LocaleChar125DefaultRouteRouteWithChildren =
  Char123LocaleChar125DefaultRouteRoute._addFileChildren(
    Char123LocaleChar125DefaultRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125AuthRouteRoute:
    Char123LocaleChar125AuthRouteRouteWithChildren,
  Char123LocaleChar125DefaultRouteRoute:
    Char123LocaleChar125DefaultRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
